# Generated by Django 3.2.3 on 2021-06-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_achp_adminsignup_edit_testimonials_editsurvey_edituser_signup_uchp_uquest_usercreatesurvey_useredits'),
    ]

    operations = [
        migrations.AddField(
            model_name='edituser',
            name='accnt',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
