# Generated by Django 3.2.3 on 2021-06-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_add_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_testimonials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
