# Generated by Django 3.2.3 on 2021-06-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0006_uquest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uquest',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
