# Generated by Django 3.2.3 on 2021-06-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0008_auto_20210611_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edituser',
            name='accnt',
            field=models.CharField(choices=[('Upgraded', 'Upgraded'), ('Free', 'Free')], max_length=50),
        ),
    ]
