# Generated by Django 3.2.3 on 2021-06-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_alter_edituser_accnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editsurvey',
            name='effect',
            field=models.CharField(choices=[('Effect-1', 'Effect-1'), ('Effect-2', 'Effect-2'), ('Effect-3', 'Effect-3'), ('Effect-4', 'Effect-4'), ('Effect-5', 'Effect-5'), ('Effect-6', 'Effect-6'), ('Effect-7', 'Effect-7'), ('Effect-8', 'Effect-8'), ('Effect-9', 'Effect-9'), ('Effect-10', 'Effect-10')], max_length=50),
        ),
    ]
