# Generated by Django 3.2.3 on 2021-06-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_alter_editsurvey_effect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edituser',
            old_name='accnt',
            new_name='info',
        ),
    ]
