# Generated by Django 3.2.3 on 2021-06-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0012_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uquest',
            name='date',
        ),
    ]
