# Generated by Django 3.2.3 on 2021-06-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0013_remove_uquest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edituser',
            name='info',
        ),
        migrations.AddField(
            model_name='edituser',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
