# Generated by Django 3.2.3 on 2021-06-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0015_alter_edituser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='addsurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('footer', models.CharField(max_length=50)),
                ('effect', models.CharField(choices=[('Effect-1', 'Effect-1'), ('Effect-2', 'Effect-2'), ('Effect-3', 'Effect-3'), ('Effect-4', 'Effect-4'), ('Effect-5', 'Effect-5'), ('Effect-6', 'Effect-6'), ('Effect-7', 'Effect-7'), ('Effect-8', 'Effect-8'), ('Effect-9', 'Effect-9'), ('Effect-10', 'Effect-10')], max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='editsurvey',
        ),
    ]
