# Generated by Django 3.2.3 on 2021-06-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0017_alter_addsurvey_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_testimonials',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default=None, max_length=100),
        ),
    ]
