# Generated by Django 3.2.3 on 2021-06-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0018_add_testimonials_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_testimonials',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=100),
        ),
    ]
