# Generated by Django 3.2.3 on 2021-06-29 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0021_remove_uquest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='uquest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
