# Generated by Django 3.2.3 on 2021-06-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0022_uquest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uquest',
            name='date',
        ),
    ]
