# Generated by Django 3.2.3 on 2021-06-29 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0025_alter_uquest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsurvey',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Date'),
        ),
    ]
