# Generated by Django 3.2.3 on 2021-06-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0028_signup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uquest',
            name='name',
        ),
        migrations.AddField(
            model_name='uquest',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
